BASE_URL = "https://stellarburgers.nomoreparties.site/"
LOGIN_URL = f"{BASE_URL}login"
USER_DATA_URL = f"{BASE_URL}api/auth/user"
REGISTRATE_URL = f"{BASE_URL}register"
REGISTRATE_API_URL = f"{BASE_URL}api/auth/register"
DELETE_API_URL = f"{BASE_URL}api/auth/user"
ACCOUNT_URL = f"{BASE_URL}account"
RESET_URL = f"{BASE_URL}forgot-password"
RESET_PASSWORD_URL = f"{BASE_URL}reset-password"
ORDER_HISTORY_URL = f"{BASE_URL}account/order-history"
ORDER_FEED_URL = f"{BASE_URL}feed"
INGREDIENT1_URL = f"{BASE_URL}ingredient/61c0c5a71d1f82001bdaaa6c"

EMAIL = "natalya_goncharova_12@yandex.ru"
PASSWORD = "test123"
NEW_PASSWORD = "test321"
